### ISSUE TITLE
GooglePlayServicesUtil: The Google Play services resources were not found.

### ISSUE THREAD

**Issue by ErikDohmen-xx** [arleyandrada/PushClient#127]
I just got your module, but keep getting the same error on android:
[DEBUG] :  Module: Loading module: pushHelper -> Resources/pushHelper.js
[ERROR] :  GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.

The pushHelper is my own scripting with your example data on how to connect everyting. But there's an error in finding the google play services (jar). The current version I'm using is 1.12

Any suggestions?

Thanks,
Erik

**Comment by arleyandrada** [comment]
Hi Erik,

What is your appcelerator account?
I just released a new version of my PushClient module, but the Appcelerator Marketplace is too lazy to delivery the new version to the users.

**Comment by ErikDohmen-xx** [comment]
Hi Arley,

My appcelerator account is E......2BinBusiness.nl.
I've just gotten your trial version and am more than willing to get the paid version if issue is solved. Could you please inform me about updates. Do we get updates once they are there or do you just get the version there is at the moment you buy it? Otherwise it would be more convenient to buy the $5/year version which I guess you get a new version every year?

Let me know.

Best regards,

Erik

**Comment by arleyandrada** [comment]
Hi Erik,

I don't know exactly what is your problem, but none of the PushClient module users are facing this problem, even with the 1.12 version.

Some questions:
- What is the Titanium SDK version?
- Your app uses other modules?
- Have you installed the module correctly?
  http://docs.appcelerator.com/platform/latest/#!/guide/Using_a_Module

Related to the updates: there is no a regular or scheduled releases.
Updates are released when there is reported issues or when I have time to make some improvements.

There is no a SLA or support contract, but most uses are happy with my module:
https://marketplace.appcelerator.com/apps/10615?restoreSearch=true#!reviews

There is no aditional payment for updates and everybody receive all updates for free.

If you buy the "$5/year version" you will pay $5 by year, regardless how many updates are released or not.

With other options you will pay a higher value, but only one time, with or without access to the source code (slightly more expensive).

Regards,

Arley

**Comment by ErikDohmen-xx** [comment]
Hi Arley,

I'm currently using the 5.2.2 Titanium sdk and am using one other module, the bencoding.android.tools module. I'm familiar with installing modules and did install the module correctly for as far as I can see and read. Just to make sure I did reinstall the module, but still see the same problem.

Thanks for the update on the releases, I would say your prices are very compatible and I'm more than happy to pay for the service.

What I will do in the mean time is run your example app just to see whether the issue is there as well.

Thanks,

Erik

**Comment by ErikDohmen-xx** [comment]
additional info concerning the error:
[WARN] :   dalvikvm: VFY: unable to resolve static field 6899 (common_google_play_services_unknown_issue) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 6896 (common_google_play_services_notification_ticker) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 6876 (common_ic_googleplayservices) in Lcom/google/android/gms/R$drawable;
[WARN] :   dalvikvm: VFY: unable to resolve static field 6896 (common_google_play_services_notification_ticker) in Lcom/google/android/gms/R$string;
[INFO] :   dalvikvm: Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zzh
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 571: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
[ERROR] :  GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
[WARN] :   GooglePlayServicesUtil: Google Play services is missing.

**Comment by ErikDohmen-xx** [comment]
P.S. Just bought your module ;)

**Comment by arleyandrada** [comment]
"Google Play services is missing"?

Which device are you testing the app?
Google Play Services is not present only in emulators and very older devices, for which you can not use my module.

**Comment by ErikDohmen-xx** [comment]
Testing on both the native android emulator (with google play services) as well as on my own android phone.

**Comment by arleyandrada** [comment]
Please, try to create a new project, without any other modules, just to test the push notification feature in your devices... and send any other problem with console log info to me.

It's after 4:00am in Brazil.
I will finish this support session and continue tomorrow.

**Comment by ErikDohmen-xx** [comment]
Will do, thanks for the support so far and sleep well.

**Comment by michielvaneerd** [comment]
I also saw this error message in one of mine projects, but it is disappeared when I added the ti.map module to the project. As many users will have the ti.map module, I guess that's why no one reported this before.

Is the ti.map module a requirement for this module?

**Comment by arleyandrada** [comment]
There is no dependency between my module and any other modules.
However there may be conflict between the Google Play Services versions used by other modules.
