### ISSUE TITLE
application crashes

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#49]
Hi Arley,

Yes, I do have a question about using the PushClient. After I followed all the steps and ran the example application on Android v. 4.2.2, I get an alert that the registration was successful and get a registration id. But, when I send a push message to that id, the application crashes upon receipt of the message. Here's the console output:

```
[WARN] :   dalvikvm: Unable to resolve superclass of Lbr/com/arlsoft/pushclient/GCMBroadcastReceiver; (326)
[WARN] :   dalvikvm: Link of class 'Lbr/com/arlsoft/pushclient/GCMBroadcastReceiver;' failed
[WARN] :   dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41563ac8)
[ERROR] :  TiApplication: (main) [486369,1343621] Sending event: exception on thread: main msg:java.lang.RuntimeException: Unable to instantiate receiver br.com.arlsoft.pushclient.GCMBroadcastReceiver: java.lang.ClassNotFoundException: Didn't find class "br.com.arlsoft.pushclient.GCMBroadcastReceiver" on path: /data/app/com.push-1.apk; Titanium 3.2.2,2014/03/05 12:22,96e9a07
```

It appears that the "GCMBroadcastReceiver" class cannot be found. Do you know how I can fix this?

Thank you

**Comment by arleyandrada** [comment]
Maybe you can share your project with me?
I never saw this error before, but I'd like to help you.

I suggest you to try to cleanup your project, manually delete "build" and "Resources" folder (if it's an Alloy project) and build / publish your project again.

Please let me know if that worked.

Regards,

Arley

**Comment by somefakeuser** [comment]
Sure. Here is the project file. It is the same as the example file.

I tried deleting the 'build' and the 'resources' directories, but still the same error.

[ attachment removed ]

**Comment by arleyandrada** [comment]
I need the entire project with all files or some reduced version of your application where the problem still Occurs. 

Could you share that with me?

Regards,

Arley

**Comment by somefakeuser** [comment]
Sure. Here is the entire project with all the files.

Where is the file "br.com.arlsoft.pushclient.GCMBroadcastReceiver" supposed to be located? How can I verify it is there?

[ attachment removed ]

**Comment by arleyandrada** [comment]
There is some incompatibility between the PushClient latest version (1.3) and the Titanium SDK prior to 3.2.3.GA.

Please, change your app to use Titanium SDK 3.2.3.GA or 3.3.0 until I can find some solution to this incompatibility problem.

Thanks,

Arley

**Comment by somefakeuser** [comment]
OK, I'll try a different Titanium SDK version. What is the latest Titanium SDK version that PushClient works with?

**Comment by arleyandrada** [comment]
It's working fine with SDK 3.2.3 and 3.3.0 (latest).

It should works with SDK 1.8.0 and up, but I need to fix it.

**Comment by arleyandrada** [comment]
I made some tests and I decided to fix the the minimum Titanium SDK version to 3.2.1, due to some Android specific features.

In the next days a new version of my module will be released at Titanium Marketplace.

Attached I send to you the new fixed version of my PushClient module, but your trial period was expired.

Please buy at last one "One Time Edition" seat from my PushClient module in order to continue with your tests and be allowed to use it in any of your projects.

Please let me know if you need anything else.

Thanks,

Arley

[ attachment removed ]

**Comment by somefakeuser** [comment]
Hi Arley,

This is great! There is no crash now and the app receives notifications. We will difinitely buy your module and thank you for helping.

Can you tell us with one more thing though. I read in the Android GCM documentation (http://developer.android.com/google/gcm/gcm.html) that an application should be able to recieve a push notification, even when it is not running. An iOS app can receive notifications, when it is in background (https://developer.apple.com/notifications/). But, the example you provided does not seem to receive notifications when it is not running. Is there anything extra we need to do enable the app to receive notifications on Android and iOS, when it is not running?

-s

**Comment by arleyandrada** [comment]
You are right, but...

With an native Android app you have to write and register an BroadcastReceiver class to receive a push notification, even when it is not running. My module uses this class to deal with received push notification and, according to the message attributes, it shows the local notification with light, sound, etc... Unfortunately there is no way to communicate from this background thread with the Titanium Javascript code; At this moment the application is not started.

With iOS 7 you can use the "remote notification" to ask the iOS to wake up the app (without to put it in foreground) if an push notification is received with the "content-available" attribute; In this case you must to set "remote-notification" at UIBackgroundModes in tiapp.xml, exactly as registered in my module documentation, and handle this received notification with the callback event.

http://docs.appcelerator.com/platform/latest/#!/guide/iOS_Background_Services

But with iOS 7, even as a native application, if your app has been killed trough the new multtask menu, it will not be waked up to receive the notification.

Please, let me know what exactly you want to do, and maybe I can help you.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley,

Do you know by any chance, how to make it, so that the app does not restart each time a user clicks on the notification on Android? Currently, the app restarts and the PushClient.MODE_CLICK event does not fire.

-s

**Comment by arleyandrada** [comment]
Can you share again your project with me... or your full Titanium console log?

With your previous shared project everything works fine, with any Titanium SDK version (from 3.2.1 to 3.3.0).

Regards,

Arley

**Comment by somefakeuser** [comment]
Also, I noticed that PushClient.unregisterPush(); generates the "undefined is not a function" error on iOS. Have you seen that?

**Comment by somefakeuser** [comment]
This is the project that generates an error when calling PushClient.unregisterPush() on iOS.

[ attachment removed ]

**Comment by arleyandrada** [comment]
Sorry by this bug.
Attached is a new fixed version of the module.

Did you find a solution to the previous problem (app restarts when user clicks on the notification)?

Regards,

Arley

[ attachment removed ]

**Comment by somefakeuser** [comment]
No, looks like the "undefined" error is still happening. Could you take a look again?

**Comment by arleyandrada** [comment]
Note that I released version 1.4 for iOS; You should check if your app is using the correct version by tiapp.xml file and delete the version 1.3 which is within the modules folder. Check it and get back to me, please.

**Comment by somefakeuser** [comment]
Yes, sure. I manually unpacked the zip file and copied the contents of the \modules\iphone\br.com.arlsoft.pushclient\1.4 folder to the \modules\iphone\br.com.arlsoft.pushclient\1.3 folder in my project.

**Comment by arleyandrada** [comment]
I sent to you the version 1.4 of my module, not the version 1.3 as you described.

Everything is working for me, even using your project. 

Attached is your own project with updated PushClient module.

Sorry by my delayed response.

Please, let me know if it worked for you too.

Regards,

Arley

[ attachment removed ]

**Comment by somefakeuser** [comment]
Yes, it works. Maybe, I copied it wrong the first time.

For the Android, it shows the notification correctly and plays the default sound. But, I was not able to get it to vibrate. Using still the same project you sent me, I send the following notification from a PHP script:

```
        $message = array('alert' => 'Hello, hello, hello.', 'sound' => 'default', 'vibration' => 'default');
        $fields = array(
            'registration_ids' => $registatoin_ids,
            'data' => $message,
        );
        ...
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($fields));
        ...
```

Aparently,  "'vibration' => 'default'" has no effect. Is there some flag I need to pass to make it vibrate on Android?

**Comment by somefakeuser** [comment]
Never mind! I found in your comments that it is supposed to be 'vibrate' => true. That works now.

One last thing, on iOS in the same project, I noticed that the PushClient.MODE_BACKGROUND event is not firing (there is no alert from it). Is there anything special that needs to be done to the app, like set background execution or something, to make it execute code on PushClient.MODE_BACKGROUND event?

**Comment by arleyandrada** [comment]
:-)

On iOS you will receive the MODE_BACKGROUND event if you enable the "remote-notification" option:
Set "remote-notification" at UIBackgroundModes in tiapp.xml and send a notification with "content-available" attribute.

With iOS 7 you can use the "remote notification" to ask the iOS to wake up the app (without to put it in foreground) if an push notification is received with the "content-available" attribute, as documentation.

http://docs.appcelerator.com/platform/latest/#!/guide/iOS_Background_Services

There is an "bug" in iOS 7: even as a native application, if your app has been killed trough the new multtask menu, it will not be waked up to receive the "background" notification.

Please, let me know if it works to you.

Regards,

Arley

**Comment by somefakeuser** [comment]
Yes, that works!

Also, do you know how to clear all notifications on Android. On iOS, I found that Ti.UI.iPhone.appBadge = 0; clears all notifications. Is there something similar for Android?

**Comment by arleyandrada** [comment]
```
Ti.Android.NotificationManager.cancelAll();
```

Please write an (good) review to my module:
https://marketplace.appcelerator.com/apps/10615?restoreSearch=true#!reviews
​
Thanks,

Arley

**Comment by somefakeuser** [comment]
Sure!

I noticed one interesting thing. Every once in a while the PushClient.ERROR_REGISTER error happens. In this case, I wait 30 seconds and call PushClient.registerPush again to retry. After that, if the registration is successful, the eventSuccess callback is now called twice, not once. It is called as many times, as PushClient.registerPush was called (including the failed ones). Is this normal? If not, what is the proper way to retry the registration?

**Comment by arleyandrada** [comment]
It's not normal.
I will try to reproduce this behavior and release a new fix to it.
Thanks again!

**Comment by somefakeuser** [comment]
Yes, please fix, if you can. I noticed that all other events, like PushClient.MODE_FOREGROUND, are also fired multiple times after that.

**Comment by arleyandrada** [comment]
I was unable to reproduce the this problematic behavior with iOS or Android, regardless of how many times I call the "registerPush" method.

Did you are not firing the "addEventListener" in duplicate together with the retry call to the "registerPush" method?

**Comment by somefakeuser** [comment]
No, I don't call addEventListener at all. If I get the registration error (service unavailable), I just call registerPush in 30 secods after that error event.

**Comment by arleyandrada** [comment]
iOS, Android or both?

Are you coding something like that:

```
PushClient.addEventListener(PushClient.EVENT_ERROR, function(event) {
    setTimeout(function(){
        PushClient.registerPush(registerOptions);
    }, 30000);
});
```

Are you putting the PushClient within some controller? If yes, try to move it to an global scope like alloy.js.

I will continue trying to reproduce the problematic behavior...

**Comment by somefakeuser** [comment]
Almost exactly like this, but in the event handler, in index.js I have:

```
    case PushClient.ERROR_REGISTER:
    setTimeout(function(){
        PushClient.registerPush(registerOptions);
    }, 30000);
```

i.e. only if a specific error unable to register occurs. It happens on Android. On iOS, I couldn't test, as it is always registered for the first time.

The way to reproduce on Android is to switch off the interenet connection and run the app. Then, switch the interenet connection back on.

**Comment by arleyandrada** [comment]
Definitely I could not reproduce the problem.
Sorry about that.

Did you find any solution?

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley,

Sorry about the dealy. I found the problem on my end. Each time the registration failed, I ran it again. At the same time, I registered the event listeners all over again. That was causing the multiple events later on. So, your code works correctly.

**Comment by arleyandrada** [comment]
I'm glad to know! 
Thanks for the feedback.

**Comment by somefakeuser** [comment]
Hi Arley,

How are you? I have another question. I just tried installing my app on a new Android device with the xxhdpi resolution. Everything works OK, but the large notification icon that shows up in the notifications list appears to be of a wrong size. It looks stretched and only the middle portion of it is showing. The small icon on the toolbar shows up correctly. Do I need to do anthing special with the icons to make make them show up correctly in the notificatonis list?

**Comment by arleyandrada** [comment]
Since PushClient version 1.6 you can send a payload data with "smallIcon" and "largeIcon" attributes.

Without custom icons my module set the app icon to both small and large icons... with no perfect fit.

Make a try and return me.

Regards,

Arley

**Comment by somefakeuser** [comment]
Where the custom icons are located? Are they shipped with the project, or can I send them from the server like a photo of a user, who sent a message?

**Comment by arleyandrada** [comment]
```
// "smallIcon" (String) set small icon to Android notification from assets
// "largeIcon" (String) set large icon to Android notification from local file or url
```
